<?php

namespace UcmBundle\Repository;

/**
 * CategformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategformationRepository extends \Doctrine\ORM\EntityRepository
{
}
