<?php

namespace UcmBundle\Repository;

use UcmBundle\Entity\Directeur;

/**
 * DirecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirecteurRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function rechercheDirecteur($param){
		
		$qb = $this->createQueryBuilder('d')
		->Where('d.nom = :nom')
		->OrWhere('d.prenom = :prenom')
		->setParameter('nom', $param)
		->setParameter('prenom', $param)
		->getQuery();

        return $qb->execute();
			
	}
	
}
