<?php

namespace UcmBundle\Repository;

use UcmBundle\Entity\Evenement;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
	public function getEvenements(){
		
		$query = $this->createQueryBuilder('e')
		->select('e')
		->where('e.actif = 1')
		->orderBy('e.id', 'DESC')
		->setMaxresults(3)
		;
		
		return $query->getQuery()->getResult();	
	}
}
