<?php

namespace UcmBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{

		public function findBySearch($params){
				//$repository = $this->getDoctrine()->getRepository(Chaise::class);		
				$query = $this->createQueryBuilder('f')					
					->where('1=1');					

					if(array_key_exists('discipline', $params) && count($params['discipline']) > 0){
						$query->andWhere("f.titre LIKE :discipline");
						$query->setParameter('discipline', $params['discipline']);
					}

					
				$result = $query->getQuery();

				$formation = $result->getResult();
				return $formation;
	}
}
