<?php

namespace UcmBundle\Repository;

/**
 * MotdirecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotdirecteurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getMotDirecteur(){
		
		$query = $this->createQueryBuilder('m')
			->join('m.directeur', 'd')
			->where('d.active = 1')
			->setMaxresults(1)
			;
			
		return $query->getQuery()->getResult();
	}

	public function rechercheMotdirecteur($param){
		$qb = $this->createQueryBuilder('m')
			->join('m.directeur', 'd')
			->Where('m.titre = :titre')
			->OrWhere('d.nom = :nom')
			->OrWhere('d.prenom = :prenom')
			->setParameter('titre', $param)
			->setParameter('nom', $param)
			->setParameter('prenom', $param)
			->getQuery();

        return $qb->execute();
		
	}
}
