<?php

namespace UcmBundle\Repository;

/**
 * TypemenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypemenuRepository extends \Doctrine\ORM\EntityRepository
{
}
